# name: Beer-Passport-Server/CD
# on: 
#   # Run this pipeline whenever the CI pipeline completes successfully 
#   workflow_run:
#     workflows: ["Beer-Passport-Server/CI"]
#     branches: [master]
#     types:
#       - completed

# jobs:
#   deploy: #
#     # The type of runner that the job will run on
#     runs-on: self-hosted

#     defaults:
#       run:
#         working-directory: /home/ubuntu/beerpassport/beer-passport-server
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - name: Pull Git Repo
#         run: sudo git pull
#       - name: Build Docker Image
#         run: sudo docker-compose build
#       - name: Run Docker Container
#         run: sudo docker-compose up -d
#       - name: Remove Containers that are not running
#         run: sudo docker container prune -f
#       - name: Remove Images that are not associated with a container
#         run: sudo docker image prune -f